[build]
  command = "npm run build"
  publish = "dist"
<<<<<<< HEAD
  base = "project/"
=======
>>>>>>> c4a2740 (Initial commit with SEO and OG meta tags)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
